### PR TITLE
implementation of actor-groups

### PR DESCRIPTION
**Pull request by pjfanning**
This is just an indication of the changes I propose for https://github.com/kamon-io/Kamon/issues/101. It has no meaningful tests and has not really been tested. It is a port of something that I do have working in a private branch but that code has diverged quite a bit from kamon-akka by now.
I followed the existing actor-group structure in the kamon-akka reference.conf but I would prefer to have `actor-group` defined inside `kamon.metrics` or `kamon.metrics.filters` as opposed to `kamon`.

### CODE REVIEW

**Comment by pjfanning** [comment]
@ivantopo, @dpsoft would you be able to review this very early draft?

**Comment by pjfanning** [comment]
I have a simple demo at https://github.com/pjfanning/kamon-akka-group

**Comment by dpsoft** [comment]
@pjfanning I think that I'll can review this in the weekend.

**Comment by dpsoft** [comment]
@pjfanning I like the solution for the `actor-groups`. @ivantopo WDYT?

**Comment by pjfanning** [comment]
@dpsoft , @ivantopo I followed the existing actor-group structure in the kamon-akka reference.conf but I would prefer to have actor-group defined inside kamon.metrics or kamon.metrics.filters as opposed to kamon. See the kamon-akka-2.4.x/src/test/resources/application.conf changes in this PR for the current config.

**Comment by pjfanning** [comment]
@dpsoft @ivantopo would it be possible to consider merging this?

**Comment by dpsoft** [comment]
@pjfanning LGTM @ivantopo what do you think?

**Comment by dpsoft** [comment]
@pjfanning finally!! Thanks for proposing this PR!!!

**Pull request merged**
